name: Publish GitHub Package

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Updated Package Version and Publish'
        run: npm version patch && npm publish
        env:
          CR_PAT: $ {{ secrets.CR_PAT }}
