name: Publish GitHub Package

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kch-chiu'
      - name: 'Publish GitHub Package'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: $ {{ secrets.GITHUB_TOKEN }}
